version: '3.8'

services:
  database:    
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data    
